name = "Numav"
uuid = "8e910097-05db-4d5e-bf44-3d692aba33cf"
version = "0.1.0"
authors = ["Matheus Machado Fiuza <matheusmachadofiuza@gmail.com>"]

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
numav_julia_jll = "57785b2f-0453-510f-a9c0-981eddda5fac"

[compat]
CxxWrap = "0.17.5"
Test = "1.11.0"
numav_julia_jll = "=0.1.0"
julia = "1"
